### PR TITLE
Add a test for the binary installer and fix error when upgrading task binary

### LINKED ISSUE #164: "failed to open stream: Text file busy" while upgrading Task binary
## How
I got the error while upgrading drainpipe from 1.2.16 to 1.3.0, which included an update to the Task binary (https://github.com/Lullabot/drainpipe/pull/158).

## Why
In `vendor/lullabot/drainpipe/src/BinaryInstaller.php` we reduce the likelihood of seeing the "Text file busy" error by only copying it over when necessary. But when upgrading the Task binary, the file must still be replaced, creating an opportunity for the error to arise.

## Ideas
@deviantintegral mentioned:
> perhaps this circular dependency between task and composer should be broken. Drainpipe could validate the task version, but not actually download it (just as you have to download composer out of band to use it).

Thoughts??

### PR DESCRIPTION
**Pull request by justafish**
Here's the test failing for commit 53f88b0 https://github.com/Lullabot/drainpipe/actions/runs/8286318726/job/22676024562

Fixes #164 and #135

### CODE REVIEW

File: src/BinaryInstaller.php [hunk 1]
```diff
@@ -210,6 +210,8 @@ protected function installBinary($binary, $version, $url, $sha, $hashalgo = 'sha
         }
 
         if ('.tar.gz' === substr($fileName, -7)) {
+            // Remove .tar
+            $fs->remove(substr($cacheDestination, 0, -3));
```
Comment (mrdavidburns) [inline src/BinaryInstaller.php:214]: 💥  👍🏼

**Review by mrdavidburns — APPROVED** [review]
